### PR TITLE
Add configuration for Z axis PID control

### PR DESCRIPTION
**Pull request by veerwang**
Add configuration for Z axis PID control

### CODE REVIEW

**Comment by veerwang** [comment]
1.port PID control function
2.enable PID control function to configuration
3.fix toup camera hardware trigger bug

**Comment by veerwang** [comment]
because of backward -compatibility, reset config item of Z axis PID control to disable status

**Comment by veerwang** [comment]
add PID control arguments of flips and revolution to configuration

**Review by hongquanli — COMMENTED** [review]
naming: `pid_arg_encoder_flip_dir_x` -> `encoder_flip_dir_x`

**Comment by veerwang** [comment]
naming arguments

**Comment by veerwang** [comment]
separately configure pid control and encoder config

**Comment by veerwang** [comment]
fix a bug

**Comment by veerwang** [comment]
update and fix a bug

**Comment by veerwang** [comment]
modify function's name of configure_encoder_arguments

**Pull request merged**
